parameters:
    basecom_shopware_connector.serializer.shopware_product.class:       Basecom\Bundle\ShopwareConnectorBundle\Serializer\ShopwareProductSerializer
services:
    basecom_shopware_connector.serializer.shopware_product:
        class: %basecom_shopware_connector.serializer.shopware_product.class%
        arguments:
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.category'
#            ToDo: Warum Ã¼bergibst du hier ein Array und in der Klasse selbst ist es nur ein Wert?
            - [%kernel.root_dir%]
            - '@akeneo_file_storage.repository.file_info'
            - '@doctrine.orm.entity_manager'